### ISSUE TITLE
Cant use normal decoration Image 

### ISSUE THREAD

**Issue by Technorocker** [johynpapin/flutter_inset_shadow#10]
Hello there, I was having some issues with a container boxdecoration image showing up on one of my screens even though I use the exact same container code for every page. I recreated a duplicate page and started adding piece by piece and the problem occured when I have to Hide the boxDecoration and boxShadow from the material.dart in order for your plugin to take over. 

```
   body: Container(
        decoration: const BoxDecoration(
          image: DecorationImage(
            image: AssetImage(
                'assets/images/curcuit_background-3.png'), // TODO not showing image
            fit: BoxFit.cover,
          ),
        ),
```

This is the snippet I use for the page background. I am using youre inset for a timer button on the screen but I need to be able to have both a background image as well as the inset button on the same page.

Any suggestions?

**Comment by ghost** [comment]
Hello,

Looks like a bug! I'll try to find some time to have a look. Thank you very much for taking the time to write an issue!

However, you should know that I can't currently deploy updates for this package, you can find out more here: https://github.com/johynpapin/flutter_inset_box_shadow/issues/7#issuecomment-1561375413.

Have a nice day!

**Comment by Technorocker** [comment]
Much appreciated, Ive been scratching my head as to why my image wasnt showing up for awhile now lol. I finally took some time to duplicate the page to figure it out. Not sure why the regular usage would stop working. 

I can give you a bit more info on how im suing it to hopefully help you figure out the bug.

So I have the body root as the container pushing the decoration image then a child of container is a column widget. In that column I have a button using youre plugin to start and stop recording. 

```
 AnimatedContainer(
        duration: const Duration(milliseconds: 100),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30),
          color: kPrimaryColor,
          boxShadow: [
            BoxShadow(
              blurRadius: blur,
              offset: -distance,
              color: vextSecondarySwatch.shade100,
              inset: isRecording,
            ),
            BoxShadow(
              blurRadius: blur,
              offset: distance,
              color: vextSecondarySwatch.shade800,
              inset: isRecording,
            ),
          ],
        ),
        child: Padding(
          padding: const EdgeInsets.all(15.0),
          child: Icon(
            icon,
            size: 100,
            color: primary,
          ),
        ),
      ),
```
I also notice that I use Boxdecoration in a few other parts of this page for other elements. Curious that it only doesnt work with the decoration image cause the other instances of Boxdecoration are only using color and radius parameters. 

Hope that helps you narrow down what might be causing this. :)
