### ISSUE TITLE
The method 'hashValues' isn't defined for the class 'BoxShadow' - Flutter 3.27.0

### ISSUE THREAD

**Issue by JoakoV3** [johynpapin/flutter_inset_shadow#15]
I am getting this error after updating to last flutter stable release 3.27.0

```sh
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/flutter_inset_box_shadow-1.0.8/lib/src/box_shadow.dart:124:7: 
Error: The method 'hashValues' isn't defined for the class 'BoxShadow'.
```

**Comment by chitochi** [comment]
Hi!
The package `flutter_inset_box_shadow` is now `flutter_inset_shadow` because I lost access to the account owning `flutter_inset_box_shadow` (you can read more about the change on the `README.md` of this repository).
Can you try again with `flutter_inset_shadow` version `2.0.3`?

**Comment by arturoszulc** [comment]
> Hi! The package `flutter_inset_box_shadow` is now `flutter_inset_shadow` because I lost access to the account owning `flutter_inset_box_shadow` (you can read more about the change on the `README.md` of this repository). Can you try again with `flutter_inset_shadow` version `2.0.3`?

I confirm that using `flutter_inset_shadow` solves the mentioned problem on Flutter 3.27.0

**Comment by chitochi** [comment]
yay! thanks for testing again! :tada:
