### ISSUE TITLE
The method 'hashValues' isn't defined for the class 'BoxShadow', Flutter 3.27

### ISSUE THREAD

**Issue by aminjoharinia** [johynpapin/flutter_inset_shadow#16]
Hi
In flutter 3.27 there is  this new problem
/C:/Users/$$$/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_inset_box_shadow-1.0.8/lib/src/box_shadow.dart(124,7): error GE5CFE876: The method 'hashValues' isn't defined for the class 'BoxShadow'. [D:\$$$\$$$\$$$\build\windows\x64\flutter\flutter_assemble.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(249,5): error MSB8066: Custom build for 'D:\$$$\$$$\$$$\build\windows\x64\CMakeFiles\4b9668a47793f960a7d913eccd48d635\flutter_windows.dll.rule;D:\$$$\APP\$$$\build\windows\x64\CMakeFiles\ca77b20eef0e00363f332939ca4c40b9\flutter_assemble.rule' exited with code 1. [D:\Boofi\APP\boofi\build\windows\x64\flutter\flutter_assemble.vcxproj]
Error: Build process failed.

I replace
```dart
  int get hashCode => hashValues(color, offset, blurRadius, spreadRadius, blurStyle, inset);
``` 
to
```dart
  int get hashCode => Object.hash(color, offset.dx, offset.dy, blurRadius, spreadRadius);
```

**Comment by dekadevelop** [comment]
I had the same issue just now

`
Launching lib/main.dart on Chrome in debug mode...
../../.pub-cache/hosted/pub.dev/flutter_inset_box_shadow-1.0.8/lib/src/box_shadow.dart:124:7: Error: The method 'hashValues' isn't defined for the class 'BoxShadow'.
 - 'BoxShadow' is from 'package:flutter_inset_box_shadow/src/box_shadow.dart' ('../../.pub-cache/hosted/pub.dev/flutter_inset_box_shadow-1.0.8/lib/src/box_shadow.dart').
Try correcting the name to the name of an existing method, or defining a method named 'hashValues'.
      hashValues(color, offset, blurRadius, spreadRadius, blurStyle, inset);
      ^^^^^^^^^^
Failed to compile application.
`

**Comment by chitochi** [comment]
Hi everyone!

So, please see #15, in particular https://github.com/chitochi/flutter_inset_shadow/issues/15#issuecomment-2539043585.

To avoid you a click I will just quote myself:

> The package `flutter_inset_box_shadow` is now `flutter_inset_shadow` because I lost access to the account owning `flutter_inset_box_shadow` (you can read more about the change on the `README.md` of this repository).

Using `flutter_inset_shadow` seems to fix the issue. :smile:

**Comment by chitochi** [comment]
I will take the :heart: as a hint that it works, but I will reopen the issue if I am wrong so don't hesitate. :wink:
