### ISSUE TITLE
Flutter inset Box Shadow

### ISSUE THREAD

**Issue by abdulrehmananwar** [johynpapin/flutter_inset_shadow#3]
on container shape : BoxShape.circle, its not working fine please give any solution

**Comment by ghost** [comment]
Yes sorry, at the moment it is not implemented. I'll take care of it.

In the meantime, you can try to put a very high border-radius on your container:
```dart
Container(
    decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(double.infinity),
    ),
    // ...
),
```

**Comment by ghost** [comment]
Actually I think I have implemented it, on my side it seems to work, can you give me an example that does not work please?
Thanks in advance.

**Comment by ghost** [comment]
I'm closing this issue for now because I can't reproduce it. Feel free to reopen it.
